name : CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: python:3.9
      env:
        DJANGO_SETTINGS_MODULE: myproject.settings
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10
      - name: Install dependencies
        run: |
          apt-get update;apt-get upgrade -y
          apt-get install -y python3-pip
          update-alternatives --install /usr/bin/python python /usr/bin/python3 1
          apt-get install -y libguestfs-tools python3-guestfs
          apt-get install python3-tk
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python manage.py test
