name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:latest
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: Europe/Paris
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          apt-get update;apt-get upgrade -y
          apt-get install -y python3-pip
          update-alternatives --install /usr/bin/python python /usr/bin/python3 1
          apt-get install -y libguestfs-tools python3-guestfs
          apt-get install -y python3-tk
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set time zone
        run: |
          apt-get update
          apt-get install -y tzdata
          ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime
          dpkg-reconfigure -f noninteractive tzdata
          
      - name: Run tests
        run: |
          python VSA/manage.py test ovs_conf  -v 2
      - name: create pr
        if: success()
      - uses: actions/checkout@v3
      # Make changes to pull request here
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
