name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: watar/configorci
      env:
        DEBIAN_FRONTEND: noninteractive
        TZ: Europe/Paris
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Set time zone
        run: |
          apt-get update
          apt-get install -y tzdata
          ln -fs /usr/share/zoneinfo/Europe/Paris /etc/localtime
          dpkg-reconfigure -f noninteractive tzdata
          
      - name: Run tests
        run: |
          python VSA/manage.py test ovs_conf  -v 2
